// Pool ABI for SafeBet lottery pool interactions
// This is the ABI for the safebet::pool module

export const POOL_ABI = {
  address: "0x45fffbc5d0efd8cacfdbc61af7f64b5198b4ac7b1f7f68c10f1e6b0fc4bdd193",
  name: "pool",
  friends: [],
  exposed_functions: [
    {
      name: "deposit",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64", "0x1::string::String"],
      return: [],
    },
    {
      name: "get_pool_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::string::String", "u64", "u64", "u64", "u64", "u8", "u64"],
    },
    {
      name: "get_participant_count",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_participant_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["u64", "0x1::string::String", "u64"],
    },
    {
      name: "get_outcome_total",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "0x1::string::String"],
      return: ["u64"],
    },
    {
      name: "get_winner_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::string::String", "vector<address>"],
    },
    {
      name: "is_winner",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["bool"],
    },
  ],
  structs: [],
} as const;

// Pool Factory ABI
export const POOL_FACTORY_ABI = {
  address: "0x45fffbc5d0efd8cacfdbc61af7f64b5198b4ac7b1f7f68c10f1e6b0fc4bdd193",
  name: "pool_factory",
  friends: [],
  exposed_functions: [
    {
      name: "create_pool",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "address",
        "0x1::string::String",
        "vector<0x1::string::String>",
        "u64",
        "u64",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "get_total_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_active_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<address>"],
    },
    {
      name: "get_all_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<address>"],
    },
    {
      name: "get_pool_metadata",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["address", "0x1::string::String", "u64", "u64", "bool"],
    },
  ],
  structs: [],
} as const;
