// Pool ABI for SafeBet lottery pool interactions
// This is the ABI for the safebet::pool module

export const POOL_ABI = {
  address:
    process.env.NEXT_PUBLIC_MODULE_ADDRESS || "0xb339b0b5ea892c5e3f24a0a62e22319d17d0ec6f7dff905314c6e5e9755b88ae",
  name: "pool",
  friends: [],
  exposed_functions: [
    {
      name: "deposit",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64", "0x1::string::String"],
      return: [],
    },
    {
      name: "withdraw",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "add_yield",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u64"],
      return: [],
    },
    {
      name: "lock_pool",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "set_winner",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "0x1::string::String"],
      return: [],
    },
    {
      name: "get_pool_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::string::String", "u64", "u64", "u64", "u64", "u8", "u64"],
    },
    {
      name: "get_participant_count",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_participant_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["u64", "0x1::string::String", "u64"],
    },
    {
      name: "get_outcome_total",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "0x1::string::String"],
      return: ["u64"],
    },
    {
      name: "get_winner_info",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["0x1::string::String", "vector<address>"],
    },
    {
      name: "is_winner",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["bool"],
    },
  ],
  structs: [],
} as const;

// Pool Factory ABI
export const POOL_FACTORY_ABI = {
  address:
    process.env.NEXT_PUBLIC_MODULE_ADDRESS || "0xb339b0b5ea892c5e3f24a0a62e22319d17d0ec6f7dff905314c6e5e9755b88ae",
  name: "pool_factory",
  friends: [],
  exposed_functions: [
    {
      name: "create_pool",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      // Updated params: Removed the last two u64 (durations)
      params: ["&signer", "address", "0x1::string::String", "vector<0x1::string::String>", "u64", "u64"],
      return: [],
    },
    {
      name: "get_total_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_active_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<address>"],
    },
    {
      name: "get_all_pools",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<address>"],
    },
    {
      name: "get_pool_metadata",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "address"],
      return: ["address", "0x1::string::String", "u64", "u64", "bool"],
    },
  ],
  structs: [],
} as const;
